---
title: "HW 2"
author: "AJ Catalano"
date: "11/4/2021"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

## Question 1

#### Reading and cleaning Mr. Trash Wheel data:

```{r}
trash_data =
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
             range = "Mr. Trash Wheel!A2:N535") %>%
  filter(Dumpster != "NA") %>%
  mutate_at("Sports Balls", round) %>%
  janitor::clean_names() %>%
  rename(dumpster_id = dumpster)
```

#### Reading and cleaning 2018 and 2019 precipitation data:

```{r}
# 2018 data

precipitation_2018 =
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
             range = "2018 Precipitation!A2:B14") %>%
  mutate(year = 2018) %>%
  relocate(year) %>%
  janitor::clean_names()

# 2019 data

precipitation_2019 =
  read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx",
             range = "2019 Precipitation!A2:B14") %>%
  mutate(year = 2019) %>%
  relocate(year) %>%
  janitor::clean_names()
```

#### Combining 2018 and 2019 precipitation data:

```{r}
precipitation_data = 
  bind_rows(precipitation_2018, precipitation_2019) %>%
  mutate(month = month.name[month])
```

